version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Feathers code
      - echo Running unit tests
      - yarn prod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'