version: '3'
services:
  navirego-chat-api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5001
    depends_on:
      - mongo

  
  mongo:
    image: mongo
    ports:
      - 27018:27017
